title: b.l0g.jp
url: http://b.l0g.jp
name: b.l0g.jp
permalink: pretty
paginate: 3
baseurl: ""
timezone: Japan/Tokyo
analytics_id: UA-17325326-1
sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - vendor
feed:
  path: feed/index.xml
pages_list:
  About: /about/
  Archive: /archive/
  Feed: /feed/index.xml
twitter:
  username: dblmkt
author: doublemarket
